## Pandas -- Series e Dataframes

Series e Dataframes são estruturas que facilitam a manipulação de dados em Python e, por esse motivo, são largamente utilizadas na Análise de Dados.

Pandas Series corresponde a um array unidimensional que permite indexação por meio de labels. Vamos criar uma lista que corresponde a gastos realizados em dias da semana, em seguida, vamos indexar os gastos pelos respectivos dias criando uma Series.

In [1]:
import numpy as np
import pandas as pd

In [2]:
dias = ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta']
gastos =[44, 47, 35, 52, 60]
pd.Series(gastos)

0    44
1    47
2    35
3    52
4    60
dtype: int64

In [3]:
gastos_dia = pd.Series(gastos, dias)
gastos_dia

Segunda    44
Terça      47
Quarta     35
Quinta     52
Sexta      60
dtype: int64

Agora podemos acessar os gastos usando como índices os dias.

In [4]:
gastos_dia['Sexta']

np.int64(60)

### Dataframe
Um Pandas dataframe corresponde a um vetor bidimensional (matriz), no qual é possível indexar linhas e colunas por meio de labels, e utilizar esses labels para facilitar o acesso aos dados.

Vamos criar nosso primeiro dataframe a partir de uma matriz e, em seguida, reindexar as linhas e colunas do nosso dataframe.

In [5]:
mat = np.arange(1,10).reshape(3, 3)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
pd.DataFrame(mat)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

Agora vamos criar um dataframe e reindexar suas linhas e colunas.

In [7]:
linhas = ['linha1', 'linha2', 'linha3']
colunas = ['col1', 'col2', 'col3']
df = pd.DataFrame(mat, index=linhas, columns=colunas)
df

        col1  col2  col3
linha1     1     2     3
linha2     4     5     6
linha3     7     8     9

Otenha as linhas nas quais o valor de col3 é maior que 5.

In [8]:
df[df['col3'] > 5] # df tal que df[col3] > 5

        col1  col2  col3
linha2     4     5     6
linha3     7     8     9

Obtenha as linhas nas quais o valor de col1 é menor que 5.

In [9]:
df[df['col1'] < 5]

        col1  col2  col3
linha1     1     2     3
linha2     4     5     6

É possível criar um dataframe numa única linha, informando os labels das colunas e o índices das linhas.

In [10]:
pd.DataFrame({'Col A': [1,2,3], 'Col B': [4,5,6]}, index=['primeira', 'segunda', 'terceira'])

          Col A  Col B
primeira      1      4
segunda       2      5
terceira      3      6

Exercício \

Crie um dataframe usando as listas de dias e de temperaturas (temps) a seguir. Renomei a única coluna do dataframe com o label 'Temperatura'.

In [11]:
dias = ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado', 'Domingo']
temps = [28, 25, 21, 26, 30, 31, 29]
df = pd.DataFrame({'Temperatura': temps}, index=dias)
df

         Temperatura
Segunda           28
Terça             25
Quarta            21
Quinta            26
Sexta             30
Sábado            31
Domingo           29

In [12]:
df[[['Temperatura']] == 'Quinta']

KeyError: False

### Dataset to DataFrame
Veremos agora como criar um DataFrame a partir de um dataset csv

In [ ]:
df = pd.read_csv('Piece_Dim.csv')
df.head()

  Item_No  Length  Width  Height Operator
0  Item-1  102.67  49.53   19.69     Op-1
1  Item-2  102.50  51.42   19.63     Op-1
2  Item-3   95.37  52.25   21.51     Op-1
3  Item-4   94.77  49.24   18.60     Op-1
4  Item-5  104.26  47.90   19.46     Op-1

Podemos notar que o dataset já contém um campo indexador. Vamos então utilizá-lo como índice do DataFrame.

In [ ]:
df = pd.read_csv('Piece_Dim.csv', index_col='Item_No')
df.head()

         Length  Width  Height Operator
Item_No
Item-1   102.67  49.53   19.69     Op-1
Item-2   102.50  51.42   19.63     Op-1
Item-3    95.37  52.25   21.51     Op-1
Item-4    94.77  49.24   18.60     Op-1
Item-5   104.26  47.90   19.46     Op-1

Podemos renomear as colunas de um DataFrame. Vamos passar os labels das colunas para o português.

In [ ]:
df.rename(columns={'Length': 'Comprimento', 'Width':'Largura', 'Height':'Altura', 'Operator':'Operador'}, inplace=True)
df.head()

         Comprimento  Largura  Altura Operador
Item_No
Item-1        102.67    49.53   19.69     Op-1
Item-2        102.50    51.42   19.63     Op-1
Item-3         95.37    52.25   21.51     Op-1
Item-4         94.77    49.24   18.60     Op-1
Item-5        104.26    47.90   19.46     Op-1

Podemos usar info() para obter maiores informações sobre o dataframe, assim como describe para descrevê-lo.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, Item-1 to Item-50
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Comprimento  50 non-null     float64
 1   Largura      50 non-null     float64
 2   Altura       50 non-null     float64
 3   Operador     50 non-null     object
dtypes: float64(3), object(1)
memory usage: 2.0+ KB

In [ ]:
df.describe()

       Comprimento    Largura     Altura
count    50.000000  50.000000  50.000000
mean    100.128800  49.461400  20.014000
std       5.075593   2.615639   1.074069
min      89.820000  44.460000  17.370000
25%      95.675000  48.105000  19.375000
50%      99.830000  49.315000  19.930000
75%     104.402500  50.780000  20.595000
max     110.540000  55.760000  23.110000

### Manipulação de colunas
Vamos agora manipular as colunas do nosso DataFrame, começando por selecionar a coluna 'Comprimento'.

In [ ]:
df[['Comprimento']].head()

         Comprimento
Item_No
Item-1        102.67
Item-2        102.50
Item-3         95.37
Item-4         94.77
Item-5        104.26


Agora vamos selecionar 'Comprimento' e 'Largura'.

In [ ]:
df[['Comprimento', 'Largura']].head()

         Comprimento  Largura
Item_No
Item-1        102.67    49.53
Item-2        102.50    51.42
Item-3         95.37    52.25
Item-4         94.77    49.24
Item-5        104.26    47.90

A partir dos dados de comprimento, largura e altura de uma caixa, podemos obter seu volume. Vamos, então, obter o volume de cada item e criar uma nova coluna no nosso DataFrame chamada 'Volume'.

In [ ]:
df['Volume'] = df['Comprimento'] * df['Largura'] * df['Altura']
df.head()

         Comprimento  Largura  Altura Operador         Volume
Item_No
Item-1        102.67    49.53   19.69     Op-1  100128.476019
Item-2        102.50    51.42   19.63     Op-1  103460.896500
Item-3         95.37    52.25   21.51     Op-1  107186.104575
Item-4         94.77    49.24   18.60     Op-1   86796.431280
Item-5        104.26    47.90   19.46     Op-1   97184.290840

Para manter o padrão utilizado nas outras colunas, temos que limitar o valor do volume a duas casas decimais após o ponto. Vamos utilizar a função 'round' para obter este resultado.

In [ ]:
df['Volume'] = round(df['Comprimento'] * df['Largura'] * df['Altura'], 2)
df.head()

         Comprimento  Largura  Altura Operador     Volume
Item_No
Item-1        102.67    49.53   19.69     Op-1  100128.48
Item-2        102.50    51.42   19.63     Op-1  103460.90
Item-3         95.37    52.25   21.51     Op-1  107186.10
Item-4         94.77    49.24   18.60     Op-1   86796.43
Item-5        104.26    47.90   19.46     Op-1   97184.29

Se quisermos eliminar uma coluna do nosso DataFrame, basta usar a função 'drop'. Vamos eliminar a coluna 'Volume'.

In [ ]:
df = df.drop('Volume', axis=1)
df.head()

         Comprimento  Largura  Altura Operador
Item_No
Item-1        102.67    49.53   19.69     Op-1
Item-2        102.50    51.42   19.63     Op-1
Item-3         95.37    52.25   21.51     Op-1
Item-4         94.77    49.24   18.60     Op-1
Item-5        104.26    47.90   19.46     Op-1

### Manipulação de linhas
Para obter linhas (registros) específicas, usamos 'loc' ou 'iloc'. A localização se dá com base no índice utilizado no DataFrame.
Vamos começar obtendo a primeira linha (Item-1)

In [ ]:
df.loc[['Item-1' ]]

         Comprimento  Largura  Altura Operador
Item_No
Item-1        102.67    49.53   19.69     Op-1

Vamos agora filtrar os itens 1 e 5.

In [ ]:
df.loc[['Item-1', 'Item-5']]

         Comprimento  Largura  Altura Operador
Item_No
Item-1        102.67    49.53   19.69     Op-1
Item-5        104.26    47.90   19.46     Op-1

Se quisermos que no nosso resultado conste apenas Comprimento, Largura e Altura, fazemos da seguinte forma.

In [ ]:
df.loc[['Item-1', 'Item-5'], ['Comprimento', 'Largura', 'Altura']]

         Comprimento  Largura  Altura
Item_No
Item-1        102.67    49.53   19.69
Item-5        104.26    47.90   19.46

Usando iloc, temos que utilizar o índice numérico. Assim, Item-1 está na posição 0.

In [ ]:
df.iloc[[0]]

         Comprimento  Largura  Altura Operador
Item_No
Item-1        102.67    49.53   19.69     Op-1

Vamos fazer as mesmas operações que fizemos com loc agora com iloc.

In [ ]:
df.iloc[[0,4], [0,1,2]]

         Comprimento  Largura  Altura
Item_No
Item-1        102.67    49.53   19.69
Item-5        104.26    47.90   19.46

Se eu quiser selecionar os 5 primeiros registros, basta usar :5

In [ ]:
df.iloc[4:11, [0,1,2]]

         Comprimento  Largura  Altura
Item_No
Item-5        104.26    47.90   19.46
Item-6        105.18    49.39   20.36
Item-7         97.35    48.05   20.22
Item-8         99.35    44.59   21.03
Item-9         90.62    47.29   19.78
Item-10        97.22    52.14   20.71
Item-11       100.00    54.76   20.62

Suponha que queremos agora obter Comprimento e largura de todos os registros.

In [ ]:
df.iloc[:, :2]

         Comprimento  Largura
Item_No
Item-1        102.67    49.53
Item-2        102.50    51.42
Item-3         95.37    52.25
Item-4         94.77    49.24
Item-5        104.26    47.90
Item-6        105.18    49.39
Item-7         97.35    48.05
Item-8         99.35    44.59
Item-9         90.62    47.29
Item-10        97.22    52.14
Item-11       100.00    54.76
Item-12        97.23    48.26
Item-13       105.72    50.04
Item-14        89.82    45.98
Item-15        99.17    53.54
Item-16        95.51    45.36
Item-17       107.69    48.18
Item-18       106.83    50.81
Item-19        98.73    55.76
Item-20        94.31    48.74
Item-21       104.87    49.73
Item-22        98.06    48.39
Item-23       108.45    44.46
Item-24        95.34    46.03
Item-25        97.66    50.69
Item-26        95.69    49.48
Item-27       105.88    49.53
Item-28       101.68    52.79
Item-29        93.54    51.05
Item-30        99.66    48.40
Item-31        98.38    46.79
Item-32        95.53    53.83
Item-33       100.53    50.00
Item-34        95.67    49.64
Item-35       101.86    50.45
Item-36       105.22    54.61
Item-37       101.86    49.85
Item-38        97.19    49.90
Item-39       103.00    48.81
Item-40       100.57    53.52
Item-41       110.54    51.07
Item-42       109.22    45.24
Item-43        92.52    49.04
Item-44       107.05    49.01
Item-45       106.53    48.55
Item-46       101.21    47.61
Item-47       101.09    48.28
Item-48        95.61    46.30
Item-49       104.45    48.71
Item-50        93.28    48.08

Vamos agora calcular a média dos itens produzidos por cada operador (Op-1 e Op-2).

In [ ]:
df1 = df[df['Operador'] == 'Op-1']
df2 = df[df['Operador'] == 'Op-2']
print('Média do comprimento operador 1: ' + str(round(df1['Comprimento'].mean(), 2)))
print('Média do comprimento operador 2: ' + str(round(df2['Comprimento'].mean(), 2)))

Média do comprimento operador 1: 99.55
Média do comprimento operador 2: 100.71

Exercício 1\
Obter os itens cujo comprimento seja maior que 105 produzidos pelo Op-1.

In [ ]:
df[(df['Operador'] == 'Op-1') & (df['Comprimento'] > 105)]

         Comprimento  Largura  Altura Operador
Item_No
Item-6        105.18    49.39   20.36     Op-1
Item-13       105.72    50.04   20.06     Op-1
Item-17       107.69    48.18   19.33     Op-1
Item-18       106.83    50.81   19.12     Op-1
Item-23       108.45    44.46   22.31     Op-1

Exercício 2\
Obter os itens cujo comprimento seja maior que 98 e menor que 105.

In [ ]:
df[(df['Comprimento'] > 98) & (df['Comprimento'] < 105)]

         Comprimento  Largura  Altura Operador
Item_No
Item-1        102.67    49.53   19.69     Op-1
Item-2        102.50    51.42   19.63     Op-1
Item-5        104.26    47.90   19.46     Op-1
Item-8         99.35    44.59   21.03     Op-1
Item-11       100.00    54.76   20.62     Op-1
Item-15        99.17    53.54   20.25     Op-1
Item-19        98.73    55.76   19.37     Op-1
Item-21       104.87    49.73   19.94     Op-1
Item-22        98.06    48.39   19.79     Op-1
Item-28       101.68    52.79   19.42     Op-2
Item-30        99.66    48.40   20.64     Op-2
Item-31        98.38    46.79   21.27     Op-2
Item-33       100.53    50.00   21.13     Op-2
Item-35       101.86    50.45   18.05     Op-2
Item-37       101.86    49.85   19.15     Op-2
Item-39       103.00    48.81   19.39     Op-2
Item-40       100.57    53.52   19.98     Op-2
Item-46       101.21    47.61   21.39     Op-2
Item-47       101.09    48.28   20.04     Op-2
Item-49       104.45    48.71   19.51     Op-2

Exercício 3 \
Obter os itens cujo comprimento é maior ou igual a 110 OU cuja largura é maior ou igual a 53.

In [ ]:
df[(df['Comprimento'] >= 110) | (df['Largura'] >= 53)]

         Comprimento  Largura  Altura Operador
Item_No
Item-11       100.00    54.76   20.62     Op-1
Item-15        99.17    53.54   20.25     Op-1
Item-19        98.73    55.76   19.37     Op-1
Item-32        95.53    53.83   23.11     Op-2
Item-36       105.22    54.61   20.64     Op-2
Item-40       100.57    53.52   19.98     Op-2
Item-41       110.54    51.07   21.95     Op-2

In [ ]:
import seaborn as sns
df2 = sns.load_dataset('tips')
df2.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

Exercício 4 \
Selecione os registros nos quais o valor de tip é superior a 5 dólares e a conta foi paga por uma mulher

In [ ]:
df2[(df2['tip'] > 5) & (df2['sex'] == 'Female')]

     total_bill   tip     sex smoker   day    time  size
52        34.81  5.20  Female     No   Sun  Dinner     4
85        34.83  5.17  Female     No  Thur   Lunch     4
155       29.85  5.14  Female     No   Sun  Dinner     5
214       28.17  6.50  Female    Yes   Sat  Dinner     3

Exercicio 5
Selecione os registros nos quais o valor da conta foi superior a 40 dólares no janter de um domingo.

In [ ]:
df2[(df2['total_bill'] > 40) & (df2['day'] == 'Sun') & (df2['time'] == 'Dinner')]

     total_bill  tip   sex smoker  day    time  size
156       48.17  5.0  Male     No  Sun  Dinner     6
182       45.35  3.5  Male    Yes  Sun  Dinner     3
184       40.55  3.0  Male    Yes  Sun  Dinner     2

Exercício 6
Selecione os registros nos quais o valor da gorjeta foi maior que 5 dólares em refeções feitas na sexta ou no sábado

In [ ]:
df2[(df2['tip'] > 5) & ((df2['day'] == 'Sat') | (df2['day'] == 'Fri'))]

     total_bill    tip     sex smoker  day    time  size
23        39.42   7.58    Male     No  Sat  Dinner     4
59        48.27   6.73    Male     No  Sat  Dinner     4
170       50.81  10.00    Male    Yes  Sat  Dinner     3
211       25.89   5.16    Male    Yes  Sat  Dinner     4
212       48.33   9.00    Male     No  Sat  Dinner     4
214       28.17   6.50  Female    Yes  Sat  Dinner     3
239       29.03   5.92    Male     No  Sat  Dinner     3